plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"

# Add the following to activate the plugin
plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Matt Ungaro
description: A portfolio
color-scheme: light
platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/matt-ungaro/
  - name: matthewrungaro@gmail.com
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:matthewrungaro@gmail.com

navigation:
  - name: Home Page
    link: ./
  - name: Posts
    sublist:
      - name: Predicting Sleep Quality - Decision Trees with LassoCV
        link: ./Predicting_Sleep_Quality_Decision_Trees_with_LassoCV.html
      - name: Classifying Land with Random Forest (TEST)
        link: ./Classifying_Land_with_Random_Forest_Test2.html

